### ISSUE TITLE
SpaceX Dashboard Challenge

### ISSUE THREAD

**Issue by kovurumanasa** [kovurumanasa/bigbinary-interview-for-32301424#1]
https://public.3.basecamp.com/p/UGEyqrnc11MEXx8ndGmJcA49

**Comment by vinay0x** [comment]
Thank you for taking the time to do the challenge. However, I'm sorry to let you know that you didn't make it to the next round.

Please note that it is **BigBinary's policy not to discuss the reason for the rejection**. It could be because of any of the following: 
- Code quality
- Code structuring
- Meeting requirements
- Attention to detail

To keep the integrity of the test, we do not reveal the exact reason for rejection. This ends your interview process. We wish you the best!
